### PR TITLE
Add insecure option 

### PR DESCRIPTION
**Pull request by b4iterdev**
This will add Insecure option under Ingest IP input box, which will make the connection in HTTP instead of HTTPS, allowing connection to server with ```INSECURE=true```.

### CODE REVIEW

**Comment by b4iterdev** [comment]
UI Preview: 
image

**Comment by b4iterdev** [comment]
I thought having to input raw ip, instead of having to include either ```http://``` or ```https://``` is intentional tho. But leaving ingestURL for JS processing might be simpler. 

In the future we can add option to appoint another port instead of leaving ```5100``` more easily with just editing the ```frontend``` parts

Of course if you want to use that approach, I'd love to recreate a new PR for that

**Comment by DarkView** [comment]
Spectra is intended to be used with secure connections, especially the official client. 
If you are selfhosting and intending not to use secure connections, you can also add a simple http to the link you use.
The client in its current form will not be expanded on further, once we're further along with some backend work the client will receive a major overhaul that has one simple official side and a more power-user like selfhost side where things like port etc. can be specified.

**Comment by b4iterdev** [comment]
Thanks for the suggestion.

**Pull request closed without merging**
